import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from "next-auth/react"
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const [displayName, setDisplayName] = useState(" "); 
  const { data: session, status } = useSession();
  
  const fetchDisplayName = async () => {
    if (session) {
    const res = await fetch('api/youtube/channel/account');
    const data = await res.json();
    setDisplayName(data?.items[0]['snippet']['title'])
    }
  }

  useEffect(() => {
    fetchDisplayName();
  }, [session]);

  return (
    <div className={styles.container}>
      <Head>
        <title>EssenTube</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to EssenTube
        </h1>

      {session ? <h1>Welcome {displayName} </h1> : <h1>Please sign in!</h1> }

        <div className={styles.card}>
          {
            session ? <button onClick={() => signOut()}>Sign Out</button> :
            <button onClick={() => signIn("google")}>Sign in with Youtube Account</button>
          }
        </div>
      

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
